name: Publish GitHub Pages

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Hourly Weather Data
    types:
      - completed

permissions:
  contents: write

jobs:
  publish_github_pages:
    # Avoid double-runs: use workflow_run for bot commits, push for human commits
    if: github.event_name == 'workflow_run' || (github.event_name == 'push' && github.actor != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Build page
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
